#!/bin/sh -e
set -e

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
[ -z "$gofiles" ] && exit 0

unformatted=$(gofmt -l $gofiles)

# Some files are not gofmt'd. Print message and fail.

if [ -n "$unformatted" ]; then
	echo >&2 "Go files must be formatted with gofmt. Please run:"
	for fn in $unformatted; do
		echo >&2 "  gofmt -w $PWD/$fn"
	done
fi

golintpath=$(which golint)
if [ -z $golintpath ]; then
	echo "No golint, please add to path" >&2;
	exit 1;
fi

exec 5>&1
for file in "$gofiles"; do
	lintOutput="$(golint "$file" 2>&1 | tee /dev/fd/5)"
done

if [ -n "$lintOutput" ]; then 
	echo "Please fix lint output before continuing" >&2;
fi

exec 6>&1
for file in "$gofiles"; do
	govetOutput=$(go tool vet "$file" | tee /dev/fd/6)
done

if [ -n "$govetOutput" ]; then
	echo "Please fix vet errors before continuing" >&2;
fi

[ -z "${lintOutput}" -a -z "$unformatted" -a -z "$govetOutput" ] && exit 0

exit 1
